In [43]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,6,4,4]).reshape(2,5)
b = np.array([3,3,4,5,7]).reshape(5,1)
print(np.dot(a,b))

[[ 76]
 [111]]


In [44]:

a=np.array([[1],[3],[5]])
b=np.array([1,2,1,2])
print(a+b)
 

[[2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [26]:
import time 

a = np.random.rand(1000000)
b = np.random.rand(1000000)

time1 = time.time()
c = np.dot(a,b)
time2 = time.time()
print(c)
print("Vectorized version:" + str(float((time2-time1)*1000))+"ms")

c = 0
time3 = time.time()
for i in range(1000000):
    c += a[i]*b[i]
time4 = time.time()
print(c)
print("Non-Vectorized version:" +str((time4-time3)*1000))

250282.33782252195
Vectorized version:0.9679794311523438ms
250282.33782252474
Non-Vectorized version:559.5285892486572
